### ISSUE TITLE
Track not found

### ISSUE THREAD

**Issue by arvkonstantin** [nick1n/nicholast.fm#67]
Parameters:
Track Recommendations
Overall Top 200
your last.fm username arvkonstantin

Failed:
Code: 6
Track not found

Cant use this app..

**Comment by arvkonstantin** [comment]
```
callback:jQuery1112012591379123440016_1515776836978
artist:Трэвис Скотт
track:Huncho Jack
autocorrect:1
method:track.getSimilar
format:json
api_key:f750712ed70caea3272e70e48e1f464e
_:1515776837319
```

`jQuery1112012591379123440016_1515776836978({error: 6, message: "Track not found", links: []});
`

**Comment by nick1n** [comment]
@arvkonstantin Thank you for the bug report. I'll look into it! 😃

**Comment by nick1n** [comment]
@arvkonstantin It appears to be working now, I believe what happens is when there is a new song for last.fm they don't add the song to their library until the next week. I do need to handle this particular error better because it can happen in other situations.

**Comment by arvkonstantin** [comment]
thanks, working:)
