### ISSUE TITLE
Dropdown menu 2020

### ISSUE THREAD

**Issue by Tinus24** [nick1n/nicholast.fm#68]
Hi, the dropdown menu for the monthly and yearly top stops at 2019. As I would still like to use your great site in 2020, could you update this?

**Comment by nick1n** [comment]
Sorry about that, it's fixed now. Thanks for using the web app! 🙂

**Comment by matias-autio** [comment]
Soon it's time for a 2021 update ;) I just came to look at my 2020 stats because Spotify publishes theirs around this time...
